# feature/* branch test
name: Child Cache Demo
on:
  push: 
    branches: 
      - feature/*
      
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    # Next1 : enable plugin and see if hit cache - NO hit, test cache with more push
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # build to see if hit cache
    - name: Run build
      run: ./gradlew build

    # Next2 : merge plugin and see if hit cache - first main NO hit
    # Next3 : create PR2 and see cache HIT